#!/usr/bin/env bash
# Build an MCPB bundle for arxiv-mcp-server.
# Outputs: mcpb-build/arxiv-mcp-server-darwin-<arch>-<version>.mcpb
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PYTHON_BIN="${PYTHON:-python3}"
BUILD_DIR="$ROOT/mcpb-build"

"$PYTHON_BIN" - <<'PYEOF'
import sys
if sys.version_info < (3, 11):
    raise SystemExit(
        f"Python 3.11+ is required to build the MCPB bundle; got {sys.version.split()[0]}"
    )
PYEOF

VERSION="$($PYTHON_BIN - "$ROOT/pyproject.toml" <<'PYEOF'
import pathlib, re, sys
text = pathlib.Path(sys.argv[1]).read_text()
match = re.search(r'^version\s*=\s*"([^"]+)"', text, re.MULTILINE)
if not match:
    raise SystemExit('Could not find project version in pyproject.toml')
print(match.group(1))
PYEOF
)"

echo "Building arxiv-mcp-server v$VERSION MCPB bundle..."

# Clean and create structure
rm -rf "$BUILD_DIR"
mkdir -p "$BUILD_DIR/server/vendor"

# Generate a 512x512 teal icon (pure Python, no deps)
"$PYTHON_BIN" - "$BUILD_DIR/icon.png" <<'PYEOF'
import struct, zlib, sys

def make_png(width, height, r, g, b):
    def chunk(name, data):
        c = name + data
        return struct.pack('>I', len(data)) + c + struct.pack('>I', zlib.crc32(c) & 0xFFFFFFFF)
    scanline = b'\x00' + bytes([r, g, b] * width)
    return (
        b'\x89PNG\r\n\x1a\n'
        + chunk(b'IHDR', struct.pack('>IIBBBBB', width, height, 8, 2, 0, 0, 0))
        + chunk(b'IDAT', zlib.compress(scanline * height))
        + chunk(b'IEND', b'')
    )

with open(sys.argv[1], 'wb') as f:
    f.write(make_png(512, 512, 20, 108, 148))
print("Generated icon.png")
PYEOF

# Copy manifest and stamp version
"$PYTHON_BIN" - "$ROOT/manifest.json" "$BUILD_DIR/manifest.json" "$VERSION" <<'PYEOF'
import json, sys
with open(sys.argv[1]) as f:
    manifest = json.load(f)
manifest['version'] = sys.argv[3]
with open(sys.argv[2], 'w') as f:
    json.dump(manifest, f, indent=2)
    f.write('\n')
print(f"Stamped manifest version: {sys.argv[3]}")
PYEOF

# Copy server source
cp -R "$ROOT/src/arxiv_mcp_server" "$BUILD_DIR/server/arxiv_mcp_server"
echo "Copied server source"

# Vendor runtime dependencies for stdio server operation.
# Keep this list aligned with pyproject runtime dependencies. Include the PDF
# extras because download_paper falls back to PDF conversion when arXiv HTML is
# unavailable, and MCPB users should not need to install optional deps manually.
echo "Vendoring dependencies..."
"$PYTHON_BIN" -m pip install \
  --target "$BUILD_DIR/server/vendor" \
  --no-user \
  --quiet \
  "arxiv==3.0.0" \
  "httpx==0.28.1" \
  "python-dateutil==2.9.0.post0" \
  "pydantic==2.13.3" \
  "mcp==1.27.0" \
  "aiohttp==3.13.5" \
  "python-dotenv==1.2.2" \
  "pydantic-settings==2.14.0" \
  "aiofiles==25.1.0" \
  "anyio==4.13.0" \
  "pymupdf4llm==1.27.2.3" \
  "pymupdf-layout==1.27.2.3"
echo "Dependencies vendored"

# Avoid shipping generated bytecode from local source copies or import-time validation.
find "$BUILD_DIR" -type d -name __pycache__ -prune -exec rm -rf {} +
find "$BUILD_DIR" -type f \( -name '*.pyc' -o -name '*.pyo' \) -delete

# Pack with mcpb
if ! command -v npx >/dev/null 2>&1; then
  echo "ERROR: npx is required to run @anthropic-ai/mcpb" >&2
  exit 1
fi

echo "Packing..."
cd "$BUILD_DIR"
npx --yes @anthropic-ai/mcpb@2.1.2 pack

ARTIFACT=$(find "$BUILD_DIR" -maxdepth 1 -name '*.mcpb' -print -quit)
if [[ -z "$ARTIFACT" ]]; then
  echo "ERROR: no .mcpb file found after packing" >&2
  exit 1
fi

ARCH="$(uname -m)"
FINAL_ARTIFACT="$BUILD_DIR/arxiv-mcp-server-darwin-$ARCH-$VERSION.mcpb"
if [[ "$ARTIFACT" != "$FINAL_ARTIFACT" ]]; then
  mv "$ARTIFACT" "$FINAL_ARTIFACT"
fi

echo "Built: $FINAL_ARTIFACT"
